### ISSUE TITLE
How to change dialog title?

### ISSUE THREAD

**Issue by hofstede-matheus** [afollestad/digitus#13]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of this library.
- [x] I have given my issue a non-generic title.
###### Include the following:
- Library version: `0.2.12`
- Device OS version: `6.0.1`
- Device Manufacturer: `Lenovo`
- Device Name: `Moto G4`

**Comment by syariffudinzo** [comment]
Hi, it seems on 0.3.0, setTitle is not changing the title of the FingerprintDialog. can you please verify? 

here's my code:
`Digitus.init(this, getString(R.string.app_name), REQUEST_CODE, this);
FingerprintDialog fingerDialog = FingerprintDialog.show(this, getString(R.string.app_name),
REQUEST_CODE, true);
fingerDialog.setTitle(R.string.overlay_authentication_dialog_title);`

Include the following:

Library version: 0.3.0
Device OS version: Api 23 and above
Device Manufacturer: Google
Device Name: AVD
