### ISSUE TITLE
FingerPrint authentication not available

### ISSUE THREAD

**Issue by MFlisar** [afollestad/digitus#3]
The demo app says that the fingerprint authentication is not available on my device. I have a Samsung Galaxy Alpha and it has a fingerprint sensor and I checked it and I even have one finger registered and using it as the homescreen lock works just fine...

Any ideas why it's not working with the app? Does this mean my phone has the hardware, but no third party app has access to the hardware?

**Comment by afollestad** [comment]
This is for Nexus Imprint, Google's APIs for stock Android Marshmallow.

Samsung doesn't use that.
