### ISSUE TITLE
Set cancelable to false for the fingerprint dialog

### ISSUE THREAD

**Issue by mag2007** [afollestad/digitus#4]
I have problem trying to set the fingerprint dialog to .cancelable(false)
On the "normal" material dialog, i can easy add this line and the dialog will be not dismissible when i click outside the dialog.
The problem is, on my s6 edge+(Android MM), the fingerprint scanner is on the bottom of the screen, and sometimes i touch the screen. That means the dialog will be cancelled and app closes. Is there any workaround for this? Thanks

**Comment by afollestad** [comment]
`FingerprintDialog` is a `DialogFragment`, not a regular `Dialog`.

```java
FingerprintDialog dialog = // ...
dialog.setCancelable(false);
dialog.show();
```
