### ISSUE TITLE
Set style/color for Dialog

### ISSUE THREAD

**Issue by mag2007** [afollestad/digitus#5]
I am facing problems with setting background color or style for the dialog.

This code lines aren't working:

```java
FingerprintDialog dialog = new FingerprintDialog();
dialog.setStyle(DialogFragment.STYLE_NORMAL, R.style.DialogTheme);
dialog.setCancelable(false);
dialog.show(example.this, getString(R.string.app_name), 69);
```

My dialog, doesn't get colored like for example i can do it with normal alert dialog or material dialog with this code:
```java
    .backgroundColor(getResources().getColor(R.color.cardColor))
````

Is there any specific thing i am missing? I am using the new DayNight Theme as parent for my app. It works fine everywhere, except here.

Btw, `setCancelable(boolean)` is ignored for me, I still can cancel the dialog. I made a workaround for this (I call the fingerprint dialog again, if it gets canceled).

**Comment by afollestad** [comment]
I updated your description to use correct Java formatting/highlighting. 😉

If you want to change the dialog style, you copy the dialog's code into your own class. This library uses my [Material Dialogs](https://github.com/afollestad/material-dialogs) library, so `setStyle()` will have no effect. `setCancelable(boolean)` should still work, however.

**Comment by afollestad** [comment]
Either way, this library will work without a dialog using the APIs provided. So you could always make your own custom UI, too.
