### ISSUE TITLE
not working in redmi note 3 :(

### ISSUE THREAD

**Issue by vishalpatelinexture** [afollestad/digitus#8]
MY question :

###### Include the following:
 - Library version: `latest`
 - Device OS version: `5.1.1`
 - Device Manufacturer: `xiami`
 - Device Name: `readmi note 3`

this is not working in redmi note 3.message **# " Fingerprint authentication is not available to this device."**

what is actual reason can u suggest me??

xiami have Own FIDO API?

**Comment by afollestad** [comment]
I his library is for the stock fingerprint API on Nexus devices.
