### ISSUE TITLE
can't authenticate with mobile password

### ISSUE THREAD

**Issue by vishalpatelinexture** [afollestad/digitus#9]
###### Include the following:
 - Library version: `latest`
 - Device OS version: `6.0.1`
 - Device Manufacturer: `Huawei`
 - Device Name: `Nexus 6P`

can't authenticate with mobile password when fingerprint not available.

but when i type "password" its authenticated by dialog.

how to authenticate from my mobile security paswsword.

```java
 @Override
    public void onFingerprintDialogVerifyPassword(final FingerprintDialog dialog, final String password) {
        // Simulate server contact
        mButton.postDelayed(new Runnable() {
            @Override
            public void run() {

                dialog.notifyPasswordValidation(password.equals("password"));
            }
        }, 1500);
    }
```
 
###### Reproduction Steps

1. fingerprint not available 
2. try to authenticate with password with dialog
3. cant authenticate

###### Expected Result
my mobile password is 121212  but cant authenticate.

###### Actual Result

when i type "password"  its successful

**Comment by afollestad** [comment]
That isn't a bug. The fallback password isn't using your phone password; your code above is checking is `password.equals("password"));`

**Comment by vishalpatelinexture** [comment]
is there any way to check out with my phone password ?
As like **ios** Fingerprint authentication.
